import { Inter } from "next/font/google";
import "./globals.css";
import Header from './component/header'
import Footer from './component/footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HomeEcoEarner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/style/custom.css" />
      </head>
      <body className={inter.className}>
       <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
